"""add 2FA fields

Revision ID: 0b1567f947c5
Revises: 817049c5b9f8
Create Date: 2026-08-11 14:52:56.085667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1567f947c5'
down_revision = '817049c5b9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('otp_last_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_last_sent_at')
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_hash')
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###
