"""Update notifications and settings

Revision ID: 362713df6e9f
Revises: e978edb1f41d
Create Date: 2026-08-05 10:43:42.999740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362713df6e9f'
down_revision = 'e978edb1f41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_messages_reply_to_id', 'messages', ['reply_to_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_sender_id', 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desktop_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('real_time_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('browser_notifications_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('email_notifications_enabled')
        batch_op.drop_column('real_time_notifications_enabled')
        batch_op.drop_column('desktop_notifications_enabled')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_sender_id', type_='foreignkey')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_reply_to_id', type_='foreignkey')

    # ### end Alembic commands ###
