"""Add lesson_id to Quiz

Revision ID: 4086fddf8f72
Revises: a2f38a5bd266
Create Date: 2026-07-30 19:10:49.262812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4086fddf8f72'
down_revision = 'a2f38a5bd266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_quizzes_lesson_id_lessons', 'lessons', ['lesson_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quizzes_lesson_id_lessons', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
