"""Add AI feature columns

Revision ID: 484e48f03151
Revises: 623576df2308
Create Date: 2026-08-17 10:15:26.935475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484e48f03151'
down_revision = '623576df2308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ai_chat_messages_course_id_courses', 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_quizzes_student_id_users', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quizzes_student_id_users', type_='foreignkey')
        batch_op.drop_column('student_id')
        batch_op.drop_column('is_ai_generated')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_chat_messages_course_id_courses', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
