"""Add trial eligibility to courses and lessons

Revision ID: 49e973d205e3
Revises: 211c2651e5b8
Create Date: 2026-08-19 11:44:55.406091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e973d205e3'
down_revision = '211c2651e5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial_eligible', sa.Boolean(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial_eligible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('is_trial_eligible')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('is_trial_eligible')

    # ### end Alembic commands ###
