"""add email tracking to certificate

Revision ID: 623576df2308
Revises: 0b1567f947c5
Create Date: 2026-08-13 10:52:41.228427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623576df2308'
down_revision = '0b1567f947c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
