"""Add demo video to course

Revision ID: 817049c5b9f8
Revises: c0708be67925
Create Date: 2026-08-11 10:00:48.897976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817049c5b9f8'
down_revision = 'c0708be67925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_video_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('demo_video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('demo_video_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('demo_video_file')
        batch_op.drop_column('demo_video_url')
        batch_op.drop_column('demo_video_title')

    # ### end Alembic commands ###
