"""Add chat and discussion fields

Revision ID: a41c2e417a4c
Revises: 314801e1e7a9
Create Date: 2026-07-31 12:22:44.350562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41c2e417a4c'
down_revision = '314801e1e7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('discussion_threads', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_delivered', sa.Boolean(), nullable=True))
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_messages_course_id', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_course_id', type_='foreignkey')
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_delivered')
        batch_op.drop_column('file_url')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('discussion_threads', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
