"""Add progress and attendance models

Revision ID: a4cd55cd921f
Revises: a41c2e417a4c
Create Date: 2026-08-03 10:26:31.682779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cd55cd921f'
down_revision = 'a41c2e417a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('certificate_status', sa.String(length=50), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('learning_time', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_attendance_instructor_id', 'users', ['instructor_id'], ['id'])
        batch_op.create_foreign_key('fk_attendance_lesson_id', 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_constraint('fk_attendance_instructor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_attendance_lesson_id', type_='foreignkey')
        batch_op.drop_column('remarks')
        batch_op.drop_column('attendance_date')
        batch_op.drop_column('instructor_id')
        batch_op.drop_column('lesson_id')
        
    op.drop_table('student_progress')
    op.drop_table('course_completion')

    # ### end Alembic commands ###
