"""add demo video fields to course

Revision ID: a7b88ce00446
Revises: 2bc477a9293e
Create Date: 2026-08-13 12:07:36.135802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b88ce00446'
down_revision = '2bc477a9293e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_video_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('demo_video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('demo_video_url')
        batch_op.drop_column('demo_video_title')

    # ### end Alembic commands ###
