"""Added payment models and course type

Revision ID: c0708be67925
Revises: 362713df6e9f
Create Date: 2026-08-06 18:57:19.237582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0708be67925'
down_revision = '362713df6e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('course_type')

    # ### end Alembic commands ###
