"""Update Notification and Setting models

Revision ID: c12890fb21f0
Revises: a4cd55cd921f
Create Date: 2026-08-04 10:43:11.569352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12890fb21f0'
down_revision = 'a4cd55cd921f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sound_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('browser_notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('browser_notifications_enabled')
        batch_op.drop_column('notification_sound_enabled')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('action_url')
        batch_op.drop_column('icon')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
