"""advanced_chat

Revision ID: e978edb1f41d
Revises: c12890fb21f0
Create Date: 2026-08-04 11:18:00.435939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e978edb1f41d'
down_revision = 'c12890fb21f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_announcement', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('message_type')
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('is_announcement')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_edited')

    op.drop_table('message_reactions')
    # ### end Alembic commands ###
